j-yesung/magic-pos

package.json, src/shared/supabase.ts, src/types/supabase.d.ts, yarn.lock
=> :wrench: setting: supabase 설정 파일 및 타입 생성 (#9)

src/shared/store/auth.ts, src/styles/globals.css
- global.css 상단에 tailwind 관련 코드 추가
- store 폴더 추가
=> :wrench: setting: tailwind 및 zustand 설정 (#12)

src/components/auth/User.tsx, src/hooks/auth/useAuth.ts, src/server/api/supabase/auth.ts
- session으로 페이지 접근 방지
- 비번 틀리면 알림
=> Auth UX 처리 (#10)

src/components/auth/Input.tsx, src/components/store/StoreContents.tsx, src/components/store/StoreTimeSet.tsx, src/hooks/auth/useAuth.ts, src/hooks/store/useStoreQuery.ts, src/server/api/supabase/store.ts
- 본인 가게 정보 (이메일, 사업자등록번호, 상호명)
- 영업 시간 드롭 박스
- 첫 번째 옵션(오픈 시간) 선택 시 두번째 옵션(마감 시간)은 오픈 시간 전 시간은 보이지 않습니다.
TODO
- `오픈: 00:00 마감 00:00` 으로 표기
- 텍스트 크기 조정
=> [1차] 가게 설정 (#73)

src/components/layout/admin/styles/AdminLayout.module.css, src/components/layout/home/main/StickBar.tsx, src/components/store/StoreTimeSet.tsx, src/components/store/styles/StroeContents.module.css, src/hooks/auth/useAuth.ts
- option을 완벽하게 제어하려면 React-Select, Downshift 등 라이브러리를 사용하거나 별도의 컴포넌트를 만들어야 해서 시간 관계 상 나머지 페이지 작업 후 구현해 보겠습니다.
=> 🩹 fix: 가게 설정 CSS 수정 (#73)

src/components/auth/AuthForm.tsx, src/components/auth/Input.tsx, src/components/auth/User.tsx, src/components/auth/styles/Auth.module.css, src/components/layout/home/styles/StickBar.module.css, src/hooks/auth/useAuth.ts, src/hooks/auth/useValid.ts, src/server/api/external/business.ts, yarn.lock
- 비번 확인, 사업자등록번호 인증 메세지 적용
- 모든 레이아웃 디자인 시안 적용
- 사업자등록번호 인증 버튼 모든 input 유효성 검사 완료되면 활성화 됩니다.
⎣ 인증 메세지 中 체크 표시 애니메이션은 P4
⎣ 에일리언 코드이지만 어느 부분이 드러운지 인지하고 있어서  시간 관계 상 리팩토링은 나중에 하겠습니다.
=> 로그인 & 회원가입 레이아웃 및 유효성 검사 (#10)

src/styles/reset.css
button => border:none,
a => text-decoration: none
=> :lipstick: style: reset.css 수정

src/components/layout/order/OrderLayout.tsx, src/components/layout/order/footer/AddCartButton.tsx, src/components/layout/order/footer/styles/StepButton.module.css, src/components/layout/order/styles/OrderLayout.module.css, src/components/order/cart/CartContainer.tsx, src/components/order/cart/CartOptionDetailRow.tsx, src/components/order/cart/CartOptionRow.tsx, src/components/order/cart/CartRow.tsx, src/components/order/cart/styles/CartOptionRow.module.css, src/components/order/cart/styles/CartRow.module.css, src/components/order/common/TotalPrice.tsx, src/components/order/common/style/StoreInfo.module.css, src/components/order/common/style/TotalPrice.module.css, src/components/order/menu-option/styles/MenuInfo.module.css, src/components/order/menu-option/styles/MenuOptionContainer.module.css, src/components/order/menu-option/styles/OptionRow.module.css, src/components/order/menu/styles/MenuCard.module.css, src/components/order/menu/styles/MenuCategory.module.css, src/components/order/order-type/styles/OrderTypeButton.module.css, src/components/order/order-type/styles/OrderTypeContainer.module.css, src/components/order/receipt/styles/ReceiptHeader.module.css, src/components/order/receipt/styles/ReceiptRow.module.css, src/components/order/success/styles/SuccessContainer.module.css, src/types/supabase.d.ts
=> 키오스크 장바구니 화면 수정

src/components/menu-item/MenuItemCard.tsx, src/components/menu-item/MenuItemCategory.tsx, src/components/menu-item/MenuItemFormButton.tsx, src/components/menu-item/MenuOptionModalInput.tsx, src/components/menu-item/styles/menu-item-card.module.css, src/components/menu-item/styles/menu-item-category.module.css, src/components/menu-item/styles/menu-item-form.module.css, src/components/menu-item/styles/menu-item.module.css, src/pages/admin/menu-item/index.tsx
스와이프 인덱스 확인해서 좌우 그라데이션 효과 추가했습니다.
플랫폼 참고해서 css 추가했습니다
=> 메뉴 아이템 swiper css 추가

src/components/layout/admin/AdminLayout.tsx, src/components/layout/admin/header/HeaderToggleButton.tsx, src/components/layout/admin/nav/Sidebar.tsx, src/components/layout/admin/nav/SidebarList.tsx, src/components/layout/admin/styles/AdminLayout.module.css, src/data/admin-categories.ts, src/data/admin.ts, src/shared/store/sidebar.ts, src/shared/store/toggle.ts
sidebarList import css 모듈 타입 에러 있는데 류제천 튜터님에게 브랜치 공유 후 해결 중이십니다.
=> side bar in development

src/components/menu-item/MenuItem.tsx
- 특정 카테고리에 메뉴가 하나도 없을땐 추가 안되는 에러 수정
=> 🐛 bugfix: 메뉴 추가 버그 수정 (#26)

src/components/menu-item/MenuItemContainer.tsx
- 경로 수정 한게 저장 안되고 푸시된게 있었습니다..죄송합니다..
=> 🐛 bugfix: 버그 경로 에러 수정

src/components/platform/container/Container.tsx, src/components/platform/container/card/item/Item.tsx, src/components/platform/container/card/item/styles/item.module.css, src/components/platform/container/card/styles/card.module.css, src/components/platform/container/form/Form.tsx, src/components/platform/container/form/button/styles/button.module.css
=> 💄 platform css ui 작업

src/components/toast/Toast.tsx, src/components/toast/styles/Toast.module.css, src/hooks/toast/useToast.ts, src/types/common.d.ts
*WARN*: 절대 컴포넌트가 렌더링중에 실행하지 마세요! (useEffect 안이나, 핸들러에서 호출)
- + 렌더링 중에 호출하는경우, 무한로딩되는 에러가 있어 해결했습니다.
=> :sparkles: top-center 추가 (#75)

src/components/layout/admin/SideFormLayout.tsx, src/components/layout/admin/styles/SideFormLayout.module.css, src/components/menu-category/Category.tsx, src/components/menu-category/Form.tsx, src/components/menu-category/styles/category.module.css, src/components/menu-category/styles/form.module.css, src/components/menu-item/MenuItem.tsx, src/components/menu-item/MenuItemCard.tsx, src/components/menu-item/MenuItemCategory.tsx, src/components/menu-item/MenuItemForm.tsx, src/components/menu-item/MenuItemFormButton.tsx, src/components/menu-item/MenuItemFormInput.tsx, src/components/menu-item/MenuOptionModalButton.tsx, src/components/menu-item/MenuOptionModalInput.tsx, src/components/menu-item/styles/menu-item-card.module.css, src/components/menu-item/styles/menu-item-container.module.css, src/components/menu-item/styles/menu-item-form.module.css, src/components/menu-item/styles/menu-item.module.css, src/components/menu-item/styles/menu-option-modal.module.css, src/shared/store/side-form.ts, src/styles/reset.css
- 에성님 사이드바 틀 활용
- button 태그에 회색이 기본으로  깔리는거 때문에 global.css에 button 투명화 추가했습니다.
=> 💄 style: 오른쪽 사이드 입력창 공통 컴포넌트 작업 (#138)

next.config.js, src/components/layout/admin/main/CategoryTitle.tsx, src/components/layout/admin/styles/AdminLayout.module.css, src/components/management/Management.tsx, src/components/management/managementContainer/styles/PackagingContainer.module.css, src/components/management/managementContainer/styles/ShopContainer.module.css, src/components/order-check-list/OrderCheckList.tsx, src/components/order-check-list/styles/OrderCheckList.module.css, src/pages/admin/order-check-list/index.tsx
카테고리 타이틀을 운영모드에서만 제거하고 다른 관리 페이지에서는 보입니다.
=> 💄 style: 운영모드페이지에서 공통 카테고리 타이틀 제거

src/components/management/Management.tsx, src/server/api/supabase/management.ts
TTS가 숫자를 말할때 한글로 말하는거 아라비아 숫자로 말하게 수정하였습니다.
말하는 속도도 2배빠르게 수정하였습니다
=> 🩹 fix: TTs 숫자 말할때 한글로 말하는거 아라비아 숫자로 말하게 출력 (#107)

src/components/auth/AuthForm.tsx, src/components/auth/Input.tsx, src/components/auth/button/FormButton.tsx, src/components/common/Button.tsx, src/components/layout/home/main/StartButton.tsx, src/data/input-props.ts, src/hooks/auth/useAuth.ts, src/hooks/auth/useErrorMessage.ts
- 홈에서 시작하기 버튼 클릭 시, 로그인 하지 않으면 toast 메세지 출력
- 회원가입 시, 비밀번호 유효성 검사 수정
=> QA: 로그인 & 회원가입 수정 (#150) (#151)

src/components/layout/admin/SideFormLayout.tsx, src/components/menu-category/Form.tsx, src/components/menu-item/MenuItem.tsx, src/components/menu-item/MenuItemContainer.tsx, src/components/menu-item/MenuItemFormInput.tsx, src/components/menu-item/MenuOptionModalInput.tsx, src/components/menu-item/styles/menu-item-container.module.css, src/components/menu-item/styles/menu-option-modal.module.css
- number input에서 +, -, e 들어가는 부분 수정했습니다.
- 카테고리 하나도 없을 때 메뉴 아이템 페이지 에러나는거 수정했습니다.
- 옵션같은 경우 사이드바가 접히면서 저장 폼이 사라지면서 저장이 안되던거라 사이드폼을 일단 X 버튼시에만 꺼지게 잡아놨습니다.
=> QA: 메뉴 아이템 에러 수정 (#157)

src/components/modal/default/ConfirmModal.tsx, src/components/modal/default/styles/ConfirmModal.module.css, src/components/modal/styles/Modal.module.css
=> :lipstick: style: Modal Confirm 스타일 수정

src/components/layout/admin/main/CategoryTitle.tsx, src/components/layout/admin/main/CategoryTitleIcon.tsx, src/components/layout/admin/nav/Sidebar.tsx, src/components/layout/admin/styles/AdminLayout.module.css
=> 관리자 제목 동적 생성 및 아이콘 추가 (#178)

src/components/auth/Input.tsx, src/components/auth/styles/Auth.module.css, src/components/store/StoreContents.tsx, src/components/store/StoreTimeSet.tsx, src/components/store/styles/StroeContents.module.css, src/data/input-props.ts
=> 🩹 fix: 가게 설정 틀 잡고 셀렉트 박스 포맷 변경 (#186)

src/components/management/qrCodeModal/QrCodeModal.tsx, src/components/management/qrCodeModal/packagingQrCodeContainer/PackagingQrCodeContainer.tsx, src/components/management/qrCodeModal/qrCodelistItem/styles/QrCodeListitem.module.css, src/components/management/qrCodeModal/shopQrCodeContainer/ShopQrCodeContainer.tsx, src/components/management/qrCodeModal/styles/QrCodeModal.module.css
- 동탁님 우선 버튼 분기처리 해놨고 레이아웃은 클릭할 때 , QR 노출 영역 부분만 해주시면 될 것 같습니다.
=> 🩹 fix: 모달 레이아웃 & 버튼 별 분기처리 (#205)

src/hooks/service/useKiosk.ts, src/pages/kiosk/[storeId].tsx
=> :bug: bugfix: invalid URL 오류 수정 (#251)

src/components/modal/Modal.tsx, src/components/modal/default/AlertModal.tsx, src/components/modal/styles/Modal.module.css, src/pages/kiosk/[storeId].tsx
- 모달 위에 모달 생성시 뒷 모달에 opacity 적용
=> :lipstick: style: 모달 위에 모달시 opacity 처리 (#168)

package.json, src/components/kiosk/order-type/LanguageList.tsx, src/components/kiosk/order-type/OrderTypeCard.tsx, src/components/kiosk/order-type/OrderTypeContainer.tsx, src/components/kiosk/order-type/styles/LanguageList.module.css, src/components/kiosk/order-type/styles/OrderTypeContainer.module.css, src/pages/_app.tsx, src/shared/i18n.ts, yarn.lock
=> 언어 선택 기능 개발

src/components/layout/admin/nav/SidebarList.tsx, src/components/store/sub-component/ConfirmTable.tsx, src/shared/store/table.ts
주석 확인 후 approve 하시면 삭제 후 merge 하겠습니다.
=> 🩹 fix: 테이블 사용 여부 DB 상태 변경 로직 개선 (#248)

src/components/layout/admin/nav/SendMail.tsx, src/components/layout/admin/nav/Sidebar.tsx, src/components/layout/admin/styles/SendMail.module.css, src/hooks/service/useSendEmail.ts
사이드 바 [문의하기] 버튼 클릭 시, 메세지 입력하면 제 메일로 전송됩니다.
- Input 컴포넌트 사용 실패 (경로가 없습니다.) 추후 해결 예정
=> ✨ update: 문의하기 메일 전송 기능 구현 (#271)

package.json, src/components/menu-category/Category.tsx, src/components/menu-category/CategroyCard.tsx, src/components/menu-category/styles/category.module.css, src/components/menu-item/MenuItemContainer.tsx, src/components/menu-item/items/MenuItem.tsx, src/components/menu-item/items/MenuItemCard.tsx, src/components/menu-item/items/MenuItemForm.tsx, src/components/menu-item/items/MenuItemFormInput.tsx, src/components/menu-item/options/MenuItemFormOption.tsx, src/components/menu-item/options/MenuOptionModalButton.tsx, src/components/menu-item/options/MenuOptionModalInput.tsx, src/components/menu-item/styles/menu-item-card.module.css, src/components/menu-item/styles/menu-item-form.module.css, src/hooks/menu/menu-item/useFetchMenuItems.ts, src/hooks/menu/menu-item/useSetMenuOption.ts, src/hooks/menu/menu-item/useSetMenuOptionDetail.ts, src/shared/store/menu-item.ts, yarn.lock
- 옵션 등록 체크박스 default 값이 false라 불편함 -> 옵션만 등록시 미리 true 체크 
- 메뉴 등록시 옵션과 함께 등록하면 옵션 등록안됨 -> 기존엔 바로 등록되서 됐던거라 그 부분 수정 오나료
- 메뉴 없음이 떴다가 메뉴가 뜨는 문제 -> 로딩시 빈값으로 표시
- 옵션 설정 버튼 cursor: pointer -> 수정
- 추천메뉴 checkbox 체크 제한 오류 해결 -> 5개까지만 되게
- 이미지 클릭시 이벤트 막기 -> 드래그이벤트 수정
- 드래그앤드롭 되는곳이 있고 안되는곳이있음 -> 등록시 포지션 중복 오류였음
- 드래그앤드롭시 명확하게 표시 드래그이벤트 수정
- 메뉴 관리 없음 뜨고 메뉴가 있다면 카테고리가 선택 안됨  -> 상현튜터님덕에 해결
- 메뉴 등록시 사진 표시가 느림 -> 이미지 올릴때 포멧을 변환 (nextjs sharp 라이브러리 추가)
=> 🐛 bugfix: 메뉴 아이템쪽 버그들 작업 (#282)

src/pages/kiosk/[storeId].tsx
import 잘못된거 하나 있어서 수정했습니다 .ㅠㅠㅠ
=> :ambulance: fix: 잘못된 Import 수정 (#257)

src/components/kiosk/cart/CartMoreButton.tsx, src/components/layout/order/OrderPrevButton.tsx
=> :bug: bugfix: 더 담으러 가기 오류 수정 (#280)

public/locales/en/translation.json, public/locales/ja/translation.json, public/locales/ko/translation.json, public/locales/zh/translation.json, src/server/service/translate.ts, src/utils/kiosk-helper.ts
=> :pencil2: fix: 추천메뉴 수정 (#293)

package.json, src/components/kiosk/index/IndexPageContainer.tsx, src/components/kiosk/index/QrReaderContainer.tsx, src/components/kiosk/index/styles/IndexPageContainer.module.css, src/components/kiosk/index/styles/QrReaderContainer.module.css, src/pages/kiosk/index.tsx, src/types/supabase.d.ts, yarn.lock
=> 키오스크 인덱스 페이지 레이아웃 생성

src/components/menu-item/items/MenuItemForm.tsx, src/components/menu-item/options/MenuOptionModalButton.tsx, src/components/menu-item/styles/menu-item-card.module.css, src/components/menu-item/styles/menu-item-form.module.css
=> 🩹 fix: 이미지 삭제 안되는 부분 코드 수정 (#286)

src/components/kiosk/success/SuccessContainer.tsx, src/components/management/managementSideBar/OrderItem.tsx
- 모바일 브라우저로 주문하는 경우
- 알림 허용을 하지 않은 경우
=> :bug: bugfix: 토큰을 발급받을 수 없는 경우 주문 완료 되지 않음

src/components/common/styles/Loading.module.css, src/components/modal/default/styles/DefaultModal.module.css
=> :lipstick: loading style 수정 (#379)

public/icons/exclamation-mark.svg, src/components/menu-category/Category.tsx, src/components/menu-category/styles/category.module.css, src/components/menu-item/MenuItemContainer.tsx, src/components/menu-item/items/MenuItemCategory.tsx, src/components/menu-item/items/MenuItemForm.tsx, src/components/menu-item/styles/menu-item-card.module.css, src/components/menu-item/styles/menu-item-category.module.css, src/components/menu-item/styles/menu-item-container.module.css, src/hooks/menu/menu-item/useFetchMenuItems.ts
- 메뉴 없을 때 표시 디자인대로 수정
- 메뉴카테고리, 아이템 드래그 가능 텍스트 표시 추가
- 첫메뉴 선택 안되던 버그 해결
- 모달창 닫을때 옵션 전부 표시되는 오류 해결
=> 🩹 fix: 메뉴 아이템 수정 (#286)

src/pages/_app.tsx
=> :sparkles: feat: 간격이 짧을시 로딩 화면 보여주지 않도록 수정 (간격 수정)

src/components/kiosk/cart/CartRow.tsx, src/components/kiosk/common/TotalPrice.tsx, src/components/kiosk/menu-option/MenuInfo.tsx, src/components/kiosk/menu-option/OptionDetailRow.tsx, src/components/kiosk/menu/MenuCard.tsx, src/components/kiosk/receipt/ReceiptOrderRow.tsx, src/components/kiosk/receipt/ReceiptPrice.tsx, src/components/layout/order/footer/AddCartButton.tsx, src/components/layout/order/footer/StepButton.tsx, src/shared/helper.ts
=> :sparkles: feat: convertNumberToWon 함수 변경

src/components/menu-category/CategroyCard.tsx, src/components/menu-category/styles/category.module.css, src/components/menu-item/items/MenuItemCard.tsx
=> 🩹 fix: 유저 피드백: window 드래그 이벤트 마우스 표시 문제 해결 (#286)

src/components/menu-category/styles/category.module.css, src/components/menu-item/items/form/FormItem.tsx, src/components/menu-item/items/form/RemoveItem.tsx, src/components/menu-item/styles/menu-item-card.module.css, src/hooks/menu/menu-item/useSetMenuItems.ts, src/hooks/menu/menu-item/useSetMenuOption.ts
폼 내용에 등록, 수정, 사진업로드 모여져있던거 1차적으로 한번 쪼갰습니다
=> ♻️ refactoring : moment->dayjs로 교체, 메뉴 등록폼 리팩토링

src/components/sales/calendar/cellItem/CellItem.tsx, src/components/sales/calendar/cellItem/styles/cellItem.module.css, src/components/sales/calendar/days/styles/days.module.css, src/components/sales/calendar/styles/calendar.module.css, src/components/sales/salesCalendar/salesAmount/styles/salesAmount.module.css, src/components/sales/status/chart/styles/ChartBar.module.css, src/components/sales/styles/sales.module.css, src/components/sales/toggle/tab/styles/tab.module.css, src/components/sales/toggle/toggleButton/styles/toggleButton.module.css
sales page 전체 media query 전체 적용
=> Media query/sales

src/components/menu-item/items/form/FormItem.tsx, src/components/menu-item/items/form/RemoveItem.tsx, src/components/menu-item/styles/menu-item-form.module.css, src/hooks/menu/menu-item/useSetMenuItems.ts
등록, 수정, 삭제시 loading spinner 추가했습니다
=> 🩹 fix: 메뉴 등록 모달 버튼에 loading spinner 추가

package.json, src/components/sales/Sales.tsx, src/components/sales/calendar/cell/Cell.tsx, src/components/sales/calendar/cellItem/CellItem.tsx, src/components/sales/calendar/cellItem/styles/cellItem.module.css, src/components/sales/calendarUtility/formatHoliday.ts, src/pages/admin/sales/index.tsx, src/shared/store/sales/salesHoliday.ts, src/types/sales.d.ts, yarn.lock
static props 참고해서 했는데 한번 index 파일 봐주시면 감사하겠습니다.
=> ✨ 💄  holiday 데이터 바인딩 및 style 적용

src/components/menu-category/container/card/Card.tsx, src/components/menu-category/container/form/FormCategory.tsx, src/components/menu-category/container/form/RemoveCategory.tsx, src/components/menu-item/items/card/Card.tsx, src/components/menu-item/items/form/FormItem.tsx, src/hooks/service/menu/useDragDrop.ts, src/hooks/service/menu/useOptionFiltering.ts
hooks으로 빼는 작업중인데 배포전에 일단 제일 빼야할것만 뺐습니다
=> 🚚 move: hooks 작업 중 (#286)

src/components/platform/container/form/formBody/input/Input.tsx, src/components/platform/utility/usePlatformHelper.ts, src/hooks/platform/useOgImgDebounce.ts, src/server/api/external/openGraph.ts, src/shared/store/platform.ts
=> ♻️  debounce 따로 뺌

src/components/menu-item/items/form/AddItem.tsx
메뉴도 등록시에 여러개 등록이 되서 disabled 추가 했습니다
=> 🩹 fix: 메뉴 등록 버튼 disabled 처리
